### ISSUE TITLE
Error in sprites data order in Figure 24

### ISSUE THREAD

**Issue by mvac7** [oraculo666/the_msx_red_book#2]
Hi Gustavo!
I have detected an error at the point 2 Video Display Processor in the Sprites section, in the table for detail the data order for 16x16 Sprites (Figure 24).
https://github.com/gseidler/The-MSX-Red-Book/blob/master/the_msx_red_book.md#sprites

The data from the four sections flow vertically: Up-left + Down-left + Up-right + Down-right
While the table is displayed with a horizontal flow.

You can verify this with the following example in MSX BASIC:
```
10 screen 1,2
20 for i=0 to 31
30 read A:vpoke base(9)+i,A
40 next
50 put sprite 0,(100,100),1,0
60 end
100 data 255,255,255,255
110 data 255,255,255,255
120 data 0,0,0,0
130 data 0,0,0,0
140 data 170,85,170,85
150 data 170,85,170,85
160 data 255,255,255,255
170 data 255,255,255,255
```
Show at MSXPen > WEB MSX
https://msxpen.com/?code=-M6jDV5vBLfZPATn3tGx

**Comment by gseidler** [comment]
Thank you! Verified and committed the change.
